'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { createWebSocket, getAlerts } from '../../lib/api'

export default function AlertsPage() {
  const [alerts, setAlerts] = useState<any[]>([])
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(true)
  const [liveMessage, setLiveMessage] = useState('')

  async function loadAlerts() {
    try {
      setError('')
      const data = await getAlerts()
      setAlerts(Array.isArray(data) ? data : [])
    } catch (err) {
      console.error(err)
      setError('Unable to load alerts')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    loadAlerts()

    const socket = createWebSocket((message) => {
      console.log('Alerts WS:', message)

      if (message?.type === 'alert_created') {
        setLiveMessage(`New alert: ${message.payload.message}`)
        loadAlerts()

        setTimeout(() => {
          setLiveMessage('')
        }, 4000)
      }
    })

    return () => {
      socket.close()
    }
  }, [])

  function getAlertColor(type: string) {
    if (type === 'CPU') return 'bg-orange-100 text-orange-700'
    if (type === 'TEMP') return 'bg-red-100 text-red-700'
    if (type === 'VLC') return 'bg-slate-200 text-slate-700'
    return 'bg-slate-100 text-slate-700'
  }

  if (loading) {
    return (
      <div>
        <div className="mb-6">
          <h1 className="text-2xl font-semibold">Alerts</h1>
          <p className="text-sm text-slate-500">
            Monitoring alerts generated by the backend
          </p>
        </div>

        <div className="space-y-3">
          {[1, 2, 3].map((i) => (
            <div
              key={i}
              className="h-24 animate-pulse rounded-2xl bg-slate-200"
            />
          ))}
        </div>
      </div>
    )
  }

  return (
    <div>
      <div className="mb-6">
        <h1 className="text-2xl font-semibold">Alerts</h1>
        <p className="text-sm text-slate-500">
          Monitoring alerts generated by the backend
        </p>
      </div>

      {liveMessage && (
        <div className="mb-4 rounded-xl border border-orange-300 bg-orange-50 p-3 text-orange-700">
          {liveMessage}
        </div>
      )}

      {error && (
        <div className="mb-4 rounded-xl border border-red-300 bg-red-50 p-3 text-red-700">
          {error}
        </div>
      )}

      <div className="space-y-4">
        {alerts.map((a: any) => (
          <div
            key={a.id}
            className="rounded-2xl border bg-white p-4 shadow-sm"
          >
            <div className="flex items-start justify-between gap-4">
              <div className="space-y-2">
                <div className="flex items-center gap-2">
                  <span
                    className={`rounded-full px-3 py-1 text-xs font-medium ${getAlertColor(a.type)}`}
                  >
                    {a.type}
                  </span>

                  <span className="text-xs text-slate-400">
                    {new Date(a.created_at).toLocaleString()}
                  </span>
                </div>

                <div className="text-base font-medium">{a.message}</div>

                <div className="text-sm text-slate-500">
                  Value: <b>{a.value}</b> / Threshold: <b>{a.threshold}</b>
                </div>
              </div>

              <Link
                href={`/devices/${a.device_id}`}
                className="text-sm font-medium text-slate-700 underline"
              >
                View device
              </Link>
            </div>
          </div>
        ))}

        {alerts.length === 0 && !error && (
          <div className="rounded-2xl border border-dashed p-8 text-center text-slate-500">
            No alerts found
          </div>
        )}
      </div>
    </div>
  )
}